[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "production-grade-enterprise-rag-chatbot"
version = "0.0.1"
description = "Production-grade Enterprise RAG Chatbot built with FastAPI, LangChain, Hugging Face, and Qdrant."
readme = "README.md"
requires-python = ">=3.11"

authors = [
    { name = "Sahil Kumar", email = "sahil.kr9205@gmail.com" }
]

license = { text = "MIT" }

keywords = [
    "rag",
    "llm",
    "fastapi",
    "langchain",
    "langgraph",
    "huggingface",
    "qdrant",
    "chatbot",
    "ai"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

dynamic = ["dependencies"]

[project.urls]
Homepage = ""
Repository = ""
Issues = ""

[tool.setuptools]
packages = { find = {} }

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }