"""
Schema representing the generated answer.
"""

from pydantic import BaseModel, Field, field_validator
from .finish_reason import FinishReason


class Answer(BaseModel):
    """
    Represents the answer generated by the LLM.
    """

    text: str = Field(
        ...,
        description="Generated answer.",
    )

    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Confidence score of the generated answer.",
    )

    finish_reason: FinishReason = Field(
        ...,
        description="Reason generation finished.",
    )

    @field_validator("text",)

    
    @classmethod
    def validate_strings(
        cls,
        value: str,
    ) -> str:
        """
        Validate string fields.
        """

        value = value.strip()

        if not value:
            raise ValueError(
                "Field cannot be empty."
            )

        return value